### ISSUE TITLE
Cannot find script

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/XcodeTheme#1]
Hi,

Just to let you know there's an issue with the installation procedure.

Checked out latest commit (765af248561e901101d43d0a587ada261cec2373).

```
Roberts-MacBook-Pro:Marathon robertnash$ swift build -c release -Xswiftc -static-stdlib
Compile Swift Module 'Require' (1 sources)
Compile Swift Module 'ShellOut' (1 sources)
Compile Swift Module 'Wrap' (1 sources)
Compile Swift Module 'Unbox' (42 sources)
Compile Swift Module 'Files' (1 sources)
Compile Swift Module 'Releases' (4 sources)
Compile Swift Module 'MarathonCore' (29 sources)
Compile Swift Module 'Marathon' (1 sources)
Linking ./.build/release/Marathon
Roberts-MacBook-Pro:Marathon robertnash$ marathon run johnsundell/xcodetheme
💥  Could not find a Swift script at 'johnsundell/xcodetheme.swift'
👉  Please check that the path is valid and try again
Roberts-MacBook-Pro:Marathon robertnash$ marathon run https://github.com/JohnSundell/XcodeTheme.git
💥  Could not find a Swift script at 'https://github.com/JohnSundell/XcodeTheme.git.swift'
👉  Please check that the path is valid and try again
```

**Comment by JohnSundell** [comment]
@rob-nash Thanks for the report. Do you have the latest master of Marathon installed?

**Comment by JohnSundell** [comment]
Because according to the log you posted it seems like you built it locally, but not installed it (run `make` in the Marathon folder to install it).

**Comment by rob-nash** [comment]
I had old Marathon code on disk, which I previously used to install Marathon.

I pulled from the master branch then compiled the code with

`swift build -c release -Xswiftc -static-stdlib`

I did not delete my previous installation of Marathon. I have assumed the old installation would be updated by this process.

Shall I delete my current installation and try a fresh installation using make?

**Comment by JohnSundell** [comment]
@rob-nash all you have to do is run `make` in the folder where you have cloned Marathon and it will re-compile and re-install it (you shouldn't have to delete anything if you have installed it in `/usr/local/bin`). Simply compiling the code does not install it, as the compiled binary will be put in the local `.build` directory rather than somewhere where your shell can access it 🙂

**Comment by rob-nash** [comment]
Ok, will try today.

Forgive me for asking a basic question here: In the above log, what does the following mean ?

`Linking ./.build/release/Marathon`

Confused 😢

The readme for marathon suggests the 'swift package manager' and 'cd make' are mutually exclusive options for installing. I appreciate iOS developers should probably know and understand the distinction. I confess, I am a little behind in my understanding of how Swift is utilised outside of the iOS platform.

<img width="514" alt="screen shot 2017-06-28 at 10 29 51" src="https://user-images.githubusercontent.com/14126999/27630228-c58e1e70-5bec-11e7-82cd-f6d76a88d1b7.png">

**Comment by rob-nash** [comment]
Nevermind. I have started reading about swift package manager. Thanks for our time :)
