### ISSUE TITLE
Light Mode / Dark Mode

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/XcodeTheme#2]
I use this theme all the time. It's great. Thanks for sharing.

Do you have an alternative?

If I'm coding in the evening, this theme works better. But during the day, a 'light mode' would be cool.

**Comment by rob-nash** [comment]
Your online contributions have helped me a lot (not just this repo).

Let me buy you a beer. Send me your bitcoin address.

**Comment by JohnSundell** [comment]
Hey @rob-nash 👋 Really happy you like my work, I don't use Bitcoin I'm afraid, but thanks for the offer 😄 I won't be making any other versions of this theme anytime soon, but since it's open sourced under the MIT license, anyone is free to create alternative themes based on this 🙂
