### ISSUE TITLE
Write Premissions 

### ISSUE THREAD

**Issue by MillerApps** [JohnSundell/XcodeTheme#5]
![screen shot 2018-04-06 at 5 03 46 am](https://user-images.githubusercontent.com/3836934/38413102-c911b0b2-3958-11e8-8bfd-2cdf0dce43b4.png)
Ended up installing manually😭

**Comment by ssebi** [comment]
I suggest not to install Marathon using the command "$ brew install marathon-swift". Use Make to install it which is also the recommended method:
$ git clone https://github.com/JohnSundell/Marathon.git
$ cd Marathon
$ make

**Comment by MillerApps** [comment]
When I opened this brew was the recommended installation method. Thanks for letting me know it has changed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
